/**
 * generated by Xtext 2.34.0
 */
package ld.project2.generator;

import ld.project2.thymioDSL.Action;
import ld.project2.thymioDSL.BottomSensor;
import ld.project2.thymioDSL.Model;
import ld.project2.thymioDSL.Procedure;
import ld.project2.thymioDSL.ProxSensor;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class ThymioDSLGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    fsa.generateFile("my_procedures.aesl", 
      this.generateCode(((Model) _head)));
  }

  public CharSequence generateCode(final Model m) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!DOCTYPE aesl-source>");
    _builder.newLine();
    _builder.append("<network>");
    _builder.newLine();
    _builder.append("<node>");
    _builder.newLine();
    _builder.append("var notes[6]");
    _builder.newLine();
    _builder.append("var durations[6]");
    _builder.newLine();
    _builder.append("var note_index = 6");
    _builder.newLine();
    _builder.append("var note_count = 6");
    _builder.newLine();
    _builder.append("var wave[142]");
    _builder.newLine();
    _builder.append("var i");
    _builder.newLine();
    _builder.append("var wave_phase");
    _builder.newLine();
    _builder.append("var wave_intensity");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# compute a sinus wave for sound");
    _builder.newLine();
    _builder.append("for i in 0:141 do");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("wave_phase = (i-70)*468");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("call math.cos(wave_intensity, wave_phase)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("wave[i] = wave_intensity/256");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.append("call sound.wave(wave)");
    _builder.newLine();
    _builder.append("# setup threshold for detecting claps");
    _builder.newLine();
    _builder.append("mic.threshold = 250");
    _builder.newLine();
    _builder.append("# reset outputs");
    _builder.newLine();
    _builder.append("call sound.system(-1)");
    _builder.newLine();
    _builder.append("call leds.top(0,0,0)");
    _builder.newLine();
    _builder.append("call leds.bottom.left(0,0,0)");
    _builder.newLine();
    _builder.append("call leds.bottom.right(0,0,0)");
    _builder.newLine();
    _builder.append("call leds.circle(0,0,0,0,0,0,0,0)");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# when a note is finished, play the next note");
    _builder.newLine();
    _builder.append("onevent sound.finished");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if note_index != note_count then");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("call sound.freq(notes[note_index], durations[note_index])");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("note_index += 1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("end");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("<toolsPlugins>");
    _builder.newLine();
    _builder.append("<ThymioVisualProgramming>");
    _builder.newLine();
    _builder.append("<vplroot xml-format-version=\"1\">");
    _builder.newLine();
    _builder.append("<program advanced_mode=\"0\">");
    _builder.newLine();
    _builder.newLine();
    {
      EList<Procedure> _procedures = m.getProcedures();
      for(final Procedure p : _procedures) {
        _builder.append("<set>");
        _builder.newLine();
        {
          String _button = p.getEvents().getButton();
          boolean _tripleNotEquals = (_button != null);
          if (_tripleNotEquals) {
            _builder.append("<block type=\"event\" name=\"button\" value0=\"");
            int _xifexpression = (int) 0;
            boolean _equals = p.getEvents().getButton().equals("up");
            if (_equals) {
              _xifexpression = 1;
            } else {
              _xifexpression = 0;
            }
            _builder.append(_xifexpression);
            _builder.append("\" value1=\"");
            int _xifexpression_1 = (int) 0;
            boolean _equals_1 = p.getEvents().getButton().equals("left");
            if (_equals_1) {
              _xifexpression_1 = 1;
            } else {
              _xifexpression_1 = 0;
            }
            _builder.append(_xifexpression_1);
            _builder.append("\" value2=\"");
            int _xifexpression_2 = (int) 0;
            boolean _equals_2 = p.getEvents().getButton().equals("down");
            if (_equals_2) {
              _xifexpression_2 = 1;
            } else {
              _xifexpression_2 = 0;
            }
            _builder.append(_xifexpression_2);
            _builder.append("\" value3=\"");
            int _xifexpression_3 = (int) 0;
            boolean _equals_3 = p.getEvents().getButton().equals("right");
            if (_equals_3) {
              _xifexpression_3 = 1;
            } else {
              _xifexpression_3 = 0;
            }
            _builder.append(_xifexpression_3);
            _builder.append("\" value4=\"");
            int _xifexpression_4 = (int) 0;
            boolean _equals_4 = p.getEvents().getButton().equals("center");
            if (_equals_4) {
              _xifexpression_4 = 1;
            } else {
              _xifexpression_4 = 0;
            }
            _builder.append(_xifexpression_4);
            _builder.append("\"/>");
            _builder.newLineIfNotEmpty();
          }
        }
        {
          String _stimulus = p.getEvents().getStimulus();
          boolean _tripleNotEquals_1 = (_stimulus != null);
          if (_tripleNotEquals_1) {
            _builder.append("<block type=\"event\" name=\"");
            String _xifexpression_5 = null;
            boolean _equals_5 = p.getEvents().getStimulus().equals("tap");
            if (_equals_5) {
              _xifexpression_5 = "acc";
            } else {
              _xifexpression_5 = "clap";
            }
            _builder.append(_xifexpression_5);
            _builder.append("\"/>");
            _builder.newLineIfNotEmpty();
          }
        }
        {
          ProxSensor _proxSensor = p.getEvents().getProxSensor();
          boolean _tripleNotEquals_2 = (_proxSensor != null);
          if (_tripleNotEquals_2) {
            _builder.append("<block type=\"event\" name=\"prox\" value0=\"");
            int _xifexpression_6 = (int) 0;
            String _frontLeftSensor = p.getEvents().getProxSensor().getFrontLeftSensor();
            boolean _tripleNotEquals_3 = (_frontLeftSensor != null);
            if (_tripleNotEquals_3) {
              int _xifexpression_7 = (int) 0;
              boolean _equals_6 = p.getEvents().getProxSensor().getFrontLeftSensor().equals("far");
              if (_equals_6) {
                _xifexpression_7 = 0;
              } else {
                int _xifexpression_8 = (int) 0;
                boolean _equals_7 = p.getEvents().getProxSensor().getFrontLeftSensor().equals("very_close");
                if (_equals_7) {
                  _xifexpression_8 = 1;
                } else {
                  _xifexpression_8 = 2;
                }
                _xifexpression_7 = _xifexpression_8;
              }
              _xifexpression_6 = _xifexpression_7;
            } else {
              _xifexpression_6 = 0;
            }
            _builder.append(_xifexpression_6);
            _builder.append("\" value1=\"");
            int _xifexpression_9 = (int) 0;
            String _frontCenterLeftSensor = p.getEvents().getProxSensor().getFrontCenterLeftSensor();
            boolean _tripleNotEquals_4 = (_frontCenterLeftSensor != null);
            if (_tripleNotEquals_4) {
              int _xifexpression_10 = (int) 0;
              boolean _equals_8 = p.getEvents().getProxSensor().getFrontCenterLeftSensor().equals("far");
              if (_equals_8) {
                _xifexpression_10 = 0;
              } else {
                int _xifexpression_11 = (int) 0;
                boolean _equals_9 = p.getEvents().getProxSensor().getFrontCenterLeftSensor().equals("very_close");
                if (_equals_9) {
                  _xifexpression_11 = 1;
                } else {
                  _xifexpression_11 = 2;
                }
                _xifexpression_10 = _xifexpression_11;
              }
              _xifexpression_9 = _xifexpression_10;
            } else {
              _xifexpression_9 = 0;
            }
            _builder.append(_xifexpression_9);
            _builder.append("\" value2=\"");
            int _xifexpression_12 = (int) 0;
            String _frontCenterSensor = p.getEvents().getProxSensor().getFrontCenterSensor();
            boolean _tripleNotEquals_5 = (_frontCenterSensor != null);
            if (_tripleNotEquals_5) {
              int _xifexpression_13 = (int) 0;
              boolean _equals_10 = p.getEvents().getProxSensor().getFrontCenterSensor().equals("far");
              if (_equals_10) {
                _xifexpression_13 = 0;
              } else {
                int _xifexpression_14 = (int) 0;
                boolean _equals_11 = p.getEvents().getProxSensor().getFrontCenterSensor().equals("very_close");
                if (_equals_11) {
                  _xifexpression_14 = 1;
                } else {
                  _xifexpression_14 = 2;
                }
                _xifexpression_13 = _xifexpression_14;
              }
              _xifexpression_12 = _xifexpression_13;
            } else {
              _xifexpression_12 = 0;
            }
            _builder.append(_xifexpression_12);
            _builder.append("\" value3=\"");
            int _xifexpression_15 = (int) 0;
            String _frontCenterRightSensor = p.getEvents().getProxSensor().getFrontCenterRightSensor();
            boolean _tripleNotEquals_6 = (_frontCenterRightSensor != null);
            if (_tripleNotEquals_6) {
              int _xifexpression_16 = (int) 0;
              boolean _equals_12 = p.getEvents().getProxSensor().getFrontCenterRightSensor().equals("far");
              if (_equals_12) {
                _xifexpression_16 = 0;
              } else {
                int _xifexpression_17 = (int) 0;
                boolean _equals_13 = p.getEvents().getProxSensor().getFrontCenterRightSensor().equals("very_close");
                if (_equals_13) {
                  _xifexpression_17 = 1;
                } else {
                  _xifexpression_17 = 2;
                }
                _xifexpression_16 = _xifexpression_17;
              }
              _xifexpression_15 = _xifexpression_16;
            } else {
              _xifexpression_15 = 0;
            }
            _builder.append(_xifexpression_15);
            _builder.append("\" value4=\"");
            int _xifexpression_18 = (int) 0;
            String _frontRightSensor = p.getEvents().getProxSensor().getFrontRightSensor();
            boolean _tripleNotEquals_7 = (_frontRightSensor != null);
            if (_tripleNotEquals_7) {
              int _xifexpression_19 = (int) 0;
              boolean _equals_14 = p.getEvents().getProxSensor().getFrontRightSensor().equals("far");
              if (_equals_14) {
                _xifexpression_19 = 0;
              } else {
                int _xifexpression_20 = (int) 0;
                boolean _equals_15 = p.getEvents().getProxSensor().getFrontRightSensor().equals("very_close");
                if (_equals_15) {
                  _xifexpression_20 = 1;
                } else {
                  _xifexpression_20 = 2;
                }
                _xifexpression_19 = _xifexpression_20;
              }
              _xifexpression_18 = _xifexpression_19;
            } else {
              _xifexpression_18 = 0;
            }
            _builder.append(_xifexpression_18);
            _builder.append("\" value5=\"");
            int _xifexpression_21 = (int) 0;
            String _backLeftSensor = p.getEvents().getProxSensor().getBackLeftSensor();
            boolean _tripleNotEquals_8 = (_backLeftSensor != null);
            if (_tripleNotEquals_8) {
              int _xifexpression_22 = (int) 0;
              boolean _equals_16 = p.getEvents().getProxSensor().getBackLeftSensor().equals("far");
              if (_equals_16) {
                _xifexpression_22 = 0;
              } else {
                int _xifexpression_23 = (int) 0;
                boolean _equals_17 = p.getEvents().getProxSensor().getBackLeftSensor().equals("very_close");
                if (_equals_17) {
                  _xifexpression_23 = 1;
                } else {
                  _xifexpression_23 = 2;
                }
                _xifexpression_22 = _xifexpression_23;
              }
              _xifexpression_21 = _xifexpression_22;
            } else {
              _xifexpression_21 = 0;
            }
            _builder.append(_xifexpression_21);
            _builder.append("\" value6=\"");
            int _xifexpression_24 = (int) 0;
            String _backRightSensor = p.getEvents().getProxSensor().getBackRightSensor();
            boolean _tripleNotEquals_9 = (_backRightSensor != null);
            if (_tripleNotEquals_9) {
              int _xifexpression_25 = (int) 0;
              boolean _equals_18 = p.getEvents().getProxSensor().getBackRightSensor().equals("far");
              if (_equals_18) {
                _xifexpression_25 = 0;
              } else {
                int _xifexpression_26 = (int) 0;
                boolean _equals_19 = p.getEvents().getProxSensor().getBackRightSensor().equals("very_close");
                if (_equals_19) {
                  _xifexpression_26 = 1;
                } else {
                  _xifexpression_26 = 2;
                }
                _xifexpression_25 = _xifexpression_26;
              }
              _xifexpression_24 = _xifexpression_25;
            } else {
              _xifexpression_24 = 0;
            }
            _builder.append(_xifexpression_24);
            _builder.append("\" value7=\"1000\" value8=\"2000\"/>");
            _builder.newLineIfNotEmpty();
          }
        }
        {
          BottomSensor _bottomSensor = p.getEvents().getBottomSensor();
          boolean _tripleNotEquals_10 = (_bottomSensor != null);
          if (_tripleNotEquals_10) {
            _builder.append("<block type=\"event\" name=\"proxground\" value0=\"");
            int _xifexpression_27 = (int) 0;
            boolean _equals_20 = p.getEvents().getBottomSensor().getBottomLeftSensor().equals("any");
            if (_equals_20) {
              _xifexpression_27 = 0;
            } else {
              int _xifexpression_28 = (int) 0;
              boolean _equals_21 = p.getEvents().getBottomSensor().getBottomLeftSensor().equals("white");
              if (_equals_21) {
                _xifexpression_28 = 1;
              } else {
                _xifexpression_28 = 2;
              }
              _xifexpression_27 = _xifexpression_28;
            }
            _builder.append(_xifexpression_27);
            _builder.append("\" value1=\"");
            int _xifexpression_29 = (int) 0;
            boolean _equals_22 = p.getEvents().getBottomSensor().getBottomRightSensor().equals("any");
            if (_equals_22) {
              _xifexpression_29 = 0;
            } else {
              int _xifexpression_30 = (int) 0;
              boolean _equals_23 = p.getEvents().getBottomSensor().getBottomRightSensor().equals("white");
              if (_equals_23) {
                _xifexpression_30 = 1;
              } else {
                _xifexpression_30 = 2;
              }
              _xifexpression_29 = _xifexpression_30;
            }
            _builder.append(_xifexpression_29);
            _builder.append("\" value2=\"400\" value3=\"450\"/>");
            _builder.newLineIfNotEmpty();
          }
        }
        {
          EList<Action> _actions = p.getActions();
          for(final Action a : _actions) {
          }
        }
        _builder.append("</set>");
        _builder.newLine();
      }
    }
    _builder.newLine();
    _builder.append("<set/>");
    _builder.newLine();
    _builder.append("</program>");
    _builder.newLine();
    _builder.append("</vplroot>");
    _builder.newLine();
    _builder.append("</ThymioVisualProgramming>");
    _builder.newLine();
    _builder.append("</toolsPlugins>");
    _builder.newLine();
    _builder.append("</node>");
    _builder.newLine();
    _builder.append("</network>");
    _builder.newLine();
    return _builder;
  }
}
