/*
 * generated by Xtext 2.34.0
 */
package ld.project2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ThymioDSLUiModule extends AbstractThymioDSLUiModule {

	public ThymioDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
