/**
 * generated by Xtext 2.34.0
 */
package ld.project2.thymioDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Addition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ld.project2.thymioDSL.ThymioDSLPackage#getAddition()
 * @model
 * @generated
 */
public interface Addition extends Expression
{
} // Addition
