/*
 * generated by Xtext 2.34.0
 */
package ld.project2.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import ld.project2.ide.contentassist.antlr.internal.InternalThymioDSLParser;
import ld.project2.services.ThymioDSLGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ThymioDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ThymioDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ThymioDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getOnOffAccess().getAlternatives(), "rule__OnOff__Alternatives");
			builder.put(grammarAccess.getNoteDurationAccess().getAlternatives(), "rule__NoteDuration__Alternatives");
			builder.put(grammarAccess.getOrtogonalAccess().getAlternatives(), "rule__Ortogonal__Alternatives");
			builder.put(grammarAccess.getBlackWhiteAccess().getAlternatives(), "rule__BlackWhite__Alternatives");
			builder.put(grammarAccess.getSensorStatusAccess().getAlternatives(), "rule__SensorStatus__Alternatives");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getProcedureAccess().getGroup(), "rule__Procedure__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup_2(), "rule__Event__Group_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_3(), "rule__Event__Group_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_4(), "rule__Event__Group_4__0");
			builder.put(grammarAccess.getEventAccess().getGroup_5(), "rule__Event__Group_5__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_1(), "rule__Sensor__Group_1__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_2(), "rule__Sensor__Group_2__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_3(), "rule__Sensor__Group_3__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_4(), "rule__Sensor__Group_4__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_5(), "rule__Sensor__Group_5__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_6(), "rule__Sensor__Group_6__0");
			builder.put(grammarAccess.getSensorAccess().getGroup_7(), "rule__Sensor__Group_7__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getMotorAccess().getGroup(), "rule__Motor__Group__0");
			builder.put(grammarAccess.getSoundAccess().getGroup(), "rule__Sound__Group__0");
			builder.put(grammarAccess.getSoundAccess().getGroup_3(), "rule__Sound__Group_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getOnOffAccess().getGroup_0(), "rule__OnOff__Group_0__0");
			builder.put(grammarAccess.getRBGAccess().getGroup(), "rule__RBG__Group__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup(), "rule__Addition__Group__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup_1(), "rule__Addition__Group_1__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup(), "rule__Multiplication__Group__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup_1(), "rule__Multiplication__Group_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
			builder.put(grammarAccess.getModelAccess().getProceduresAssignment(), "rule__Model__ProceduresAssignment");
			builder.put(grammarAccess.getProcedureAccess().getNameAssignment_1(), "rule__Procedure__NameAssignment_1");
			builder.put(grammarAccess.getProcedureAccess().getEventsAssignment_3(), "rule__Procedure__EventsAssignment_3");
			builder.put(grammarAccess.getProcedureAccess().getActionsAssignment_5(), "rule__Procedure__ActionsAssignment_5");
			builder.put(grammarAccess.getEventAccess().getButtonAssignment_2_1(), "rule__Event__ButtonAssignment_2_1");
			builder.put(grammarAccess.getEventAccess().getTapAssignment_3_1(), "rule__Event__TapAssignment_3_1");
			builder.put(grammarAccess.getEventAccess().getMicAssignment_4_1(), "rule__Event__MicAssignment_4_1");
			builder.put(grammarAccess.getEventAccess().getSensorAssignment_5_1(), "rule__Event__SensorAssignment_5_1");
			builder.put(grammarAccess.getSensorAccess().getBottomLeftSensorAssignment_1_1(), "rule__Sensor__BottomLeftSensorAssignment_1_1");
			builder.put(grammarAccess.getSensorAccess().getBottomRightSensorAssignment_2_1(), "rule__Sensor__BottomRightSensorAssignment_2_1");
			builder.put(grammarAccess.getSensorAccess().getNorthWestAssignment_3_1(), "rule__Sensor__NorthWestAssignment_3_1");
			builder.put(grammarAccess.getSensorAccess().getNorthNorthWestAssignment_4_1(), "rule__Sensor__NorthNorthWestAssignment_4_1");
			builder.put(grammarAccess.getSensorAccess().getNorthAssignment_5_1(), "rule__Sensor__NorthAssignment_5_1");
			builder.put(grammarAccess.getSensorAccess().getNorthNorthEastAssignment_6_1(), "rule__Sensor__NorthNorthEastAssignment_6_1");
			builder.put(grammarAccess.getSensorAccess().getNorthEastAssignment_7_1(), "rule__Sensor__NorthEastAssignment_7_1");
			builder.put(grammarAccess.getActionAccess().getMoveAssignment_1(), "rule__Action__MoveAssignment_1");
			builder.put(grammarAccess.getActionAccess().getTopLightAssignment_3(), "rule__Action__TopLightAssignment_3");
			builder.put(grammarAccess.getActionAccess().getBottomLightAssignment_5(), "rule__Action__BottomLightAssignment_5");
			builder.put(grammarAccess.getActionAccess().getSoundAssignment_7(), "rule__Action__SoundAssignment_7");
			builder.put(grammarAccess.getMotorAccess().getLeftAssignment_2(), "rule__Motor__LeftAssignment_2");
			builder.put(grammarAccess.getMotorAccess().getRightAssignment_4(), "rule__Motor__RightAssignment_4");
			builder.put(grammarAccess.getSoundAccess().getPitchAssignment_1(), "rule__Sound__PitchAssignment_1");
			builder.put(grammarAccess.getSoundAccess().getDurationAssignment_2(), "rule__Sound__DurationAssignment_2");
			builder.put(grammarAccess.getSoundAccess().getPitchAssignment_3_2(), "rule__Sound__PitchAssignment_3_2");
			builder.put(grammarAccess.getSoundAccess().getDurationAssignment_3_3(), "rule__Sound__DurationAssignment_3_3");
			builder.put(grammarAccess.getAdditionAccess().getRightAssignment_1_2(), "rule__Addition__RightAssignment_1_2");
			builder.put(grammarAccess.getMultiplicationAccess().getRightAssignment_1_2(), "rule__Multiplication__RightAssignment_1_2");
			builder.put(grammarAccess.getPrimaryAccess().getValueAssignment_0(), "rule__Primary__ValueAssignment_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ThymioDSLGrammarAccess grammarAccess;

	@Override
	protected InternalThymioDSLParser createParser() {
		InternalThymioDSLParser result = new InternalThymioDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ThymioDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ThymioDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
