/*
 * generated by Xtext 2.34.0
 */
package ld.project2.ui.tests;

import com.google.inject.Injector;
import ld.project2.ui.internal.Project2Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ThymioDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Project2Activator.getInstance().getInjector("ld.project2.ThymioDSL");
	}

}
