/*
 * generated by Xtext 2.34.0
 */
package ld.project2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractThymioDSLScopeProvider extends DelegatingScopeProvider {
}
