/**
 * generated by Xtext 2.34.0
 */
package ld.project2.thymioDSL.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import ld.project2.thymioDSL.Lights;
import ld.project2.thymioDSL.ThymioDSLFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Lights</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class LightsTest extends TestCase {

	/**
	 * The fixture for this Lights test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Lights fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(LightsTest.class);
	}

	/**
	 * Constructs a new Lights test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public LightsTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Lights test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(Lights fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Lights test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Lights getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ThymioDSLFactory.eINSTANCE.createLights());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //LightsTest
