/**
 * generated by Xtext 2.34.0
 */
package ld.project2.thymioDSL.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import ld.project2.thymioDSL.RGB;
import ld.project2.thymioDSL.ThymioDSLFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>RGB</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RGBTest extends TestCase {

	/**
	 * The fixture for this RGB test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RGB fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RGBTest.class);
	}

	/**
	 * Constructs a new RGB test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RGBTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this RGB test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(RGB fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this RGB test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RGB getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ThymioDSLFactory.eINSTANCE.createRGB());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RGBTest
